builds:
- main: ./cmd/csvq/
  ldflags:
    - -s -w # strip debug info + DWARF
    - -X main.Version={{ .Version }}
    - -X main.Commit={{ .FullCommit }}
    - -X main.Date={{ .Date }}
    - -X github.com/adamdecaf/csvq.Version={{ .Tag }}
